
BASE_DIR="/workspace"
LINUX_BASE="${BASE_DIR}/linux"
QEMU_DTS_PATH="${BASE_DIR}/qemu/overlays"
DT_FILENAME=${DT_FILENAME:-"pcdev1"}
DEVICETREE_PATH="${QEMU_DTS_PATH}/${DT_FILENAME}"
DEVICETREE_BUILD_PATH=${QEMU_DTS_PATH}/build
OUTPUT_FORMAT="dtbo"

DTC_BASE_PATH="${LINUX_BASE}/scripts/dtc"
GENERATED_DTC_PATH="${DTC_BASE_PATH}/dtc"
GENERATED_FDTOVERLAY_PATH="${DTC_BASE_PATH}/fdtoverlay"

mkdir -p ${DEVICETREE_BUILD_PATH}
echo "About to compile overlay ${DEVICETREE_PATH}.dts"
ls ${DEVICETREE_PATH}.dts

${GENERATED_DTC_PATH} -@ -I dts -O dtb -o ${DEVICETREE_BUILD_PATH}/${DT_FILENAME}.${OUTPUT_FORMAT} ${DEVICETREE_PATH}.dts
${GENERATED_FDTOVERLAY_PATH} -i ${DEVICETREE_BUILD_PATH}/${DT_FILENAME}.dtb -o ${DEVICETREE_BUILD_PATH}/${DT_FILENAME}.${OUTPUT_FORMAT} ${DEVICETREE_PATH}.dts