
BASE_DIR="/workspace"
LINUX_BASE="${BASE_DIR}/linux"
QEMU_DTS_PATH="${BASE_DIR}/qemu"
DT_FILENAME="qemu-riscv64"
DEVICETREE_PATH="${QEMU_DTS_PATH}/${DT_FILENAME}"
DEVICETREE_BUILD_PATH=${QEMU_DTS_PATH}/build

GENERATED_DTC_PATH="${LINUX_BASE}/scripts/dtc/dtc"

mkdir -p ${DEVICETREE_BUILD_PATH}
echo "About to compile ${DEVICETREE_PATH}.dts"
ls ${DEVICETREE_PATH}.dts

${GENERATED_DTC_PATH} -@ -I dts -O dtb ${DEVICETREE_PATH}.dts -o ${DEVICETREE_BUILD_PATH}/${DT_FILENAME}.dtb
